Assignment3: Point3D Class Reference
Point3D Class Reference
Header for Point3D class. Please declare your class Point3D here.
#include <point3d.hpp>
Public Member Functions
Point3D ()
Point3D Class implementation.
Point3D (double x, double y, double z)
void SetCoords (double x, double y, double z)
double DistanceTo (const Point3D p) const
double GetX () const
double GetY () const
double GetZ () const
Detailed Description
Header for Point3D class. Please declare your class Point3D here.
Constructor & Destructor Documentation
Point3D::Point3D ()
Point3D Class implementation.
Point3D::Point3D (double x, double y, double z)
Member Function Documentation
double Point3D::DistanceTo (const Point3D p) const
References GetX(), GetY(), and GetZ().
Referenced by main().
double Point3D::GetX () const
Referenced by DistanceTo().
double Point3D::GetY () const
Referenced by DistanceTo().
double Point3D::GetZ () const
Referenced by DistanceTo().
void Point3D::SetCoords (double x, double y, double z)
Referenced by main().
The documentation for this class was generated from the following files:
include/point3d.hpp
src/point3d.cpp